services:
  - type: web
    name: django-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python backend/manage.py makemigrations
      python backend/manage.py migrate
      python backend/manage.py collectstatic --noinput
      python backend/create_superuser_auto.py
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PYTHONDONTWRITEBYTECODE
        value: "true"
