# Generated by Django 5.2.6 on 2025-09-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('serie', 'Serie'), ('anime', 'Anime'), ('juego', 'Juego')], max_length=10)),
                ('imagen', models.ImageField(upload_to='favorite_items/')),
                ('resumen', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('palabras_clave', models.CharField(max_length=200)),
                ('año_lanzamiento', models.IntegerField()),
                ('link_externo', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
