# Generated by Django 5.2.6 on 2025-11-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_favoriteitem_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('curso', 'Curso'), ('diploma', 'Diploma'), ('taller', 'Taller'), ('otro', 'Otro')], default='curso', max_length=20, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('completado', 'Completado'), ('en_progreso', 'En progreso'), ('pendiente', 'Pendiente')], default='completado', max_length=20, verbose_name='Estado')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción (qué aprendiste)')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-anio', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('technologies', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('project_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='favoriteitem',
            name='imagen',
            field=models.URLField(max_length=500),
        ),
    ]
