# Generated by Django 5.2.6 on 2025-11-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_certificate_project_alter_favoriteitem_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='institucion',
            field=models.CharField(default='Desconocido', max_length=200, verbose_name='Institución'),
        ),
    ]
