# Generated by Django 5.2.6 on 2025-11-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_certificate_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='institucion',
            field=models.CharField(default='', max_length=200, verbose_name='Institución'),
        ),
    ]
